version: 0.2
run-as: root


phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 389560765612.dkr.ecr.us-east-1.amazonaws.com
      - REPOSITORY_URI=389560765612.dkr.ecr.us-east-1.amazonaws.com/cicd-ecs-demo
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t cicd-ecs-demo .
      - docker tag cicd-ecs-demo:latest 389560765612.dkr.ecr.us-east-1.amazonaws.com/cicd-ecs-demo:latest    
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 389560765612.dkr.ecr.us-east-1.amazonaws.com/cicd-ecs-demo:latest
      - echo Writing image definitions file...
artifacts:
    files: imagedefinitions.json
